### ISSUE TITLE
Aligning bottom face with z=0 plane

### ISSUE THREAD

**Issue by jphastings** [dpellegr/PolyGear#7]
I'm trying to calculate the z `transform` I'd need to bring the bottom face up to be coplanar with `z=0`.

I think I understand the [explanation in the FAQ](https://github.com/dpellegr/PolyGear#why-does-the-bottom-face-of-my-bevel-gear-lie-at-negative-z), but my (slightly rusty) geometry skills aren't bringing me the right answers.

![FAQ's diagram](https://raw.githubusercontent.com/dpellegr/PolyGear/master/imgs/bevels_sphere.svg)

As I understand it:
1. the radius of the sphere (let's call it `Rs`) is `sqrt(H0^2 + r0^2)` (where `r0` is the reference radius of the lowest part of the bevel gear — 'r ref' on the diagram — and `H0` is the height from the left end of `r0` to the centre of the sphere)
2. the distance from the origin to the lower blue line in the FAQ's diagram is the root radius  — length `rd0` (calculated as `r0 - m*(1+0.167)*(1 + ded)` in the `PolyGearBasics.scad` code, if I'm correct)
3. so the length of the line from the sphere's centre to the bevel's lower 'root surface' (the left end of that blue line) — call it `Rd` — is `sqrt(H0^2 + rd0^2)`
4. This means that distance from the edge of the sphere to the root surface (ie. the length of the "projection onto the spherical surface") is `Rp = Rs - Rd`.
5. The angle of the sphere radius that passes through that root surface from vertical — call it `θf` — is defined by `H0` and `Rd` with `tan(θf) = Rd/H0`; `θf = atan(Rd/H0)`
6. So the extra distance these bevel gears need to be lifted to have their bases coplanar with `z=0`, call it `zl`, should be: `zl = Rp * cos(θf)` so `zl = (Rs - Rd) * cos(atan(Rd/H0))` thus `zl = (Rs - Rd) / sqrt( (Rd/H0)^2 + 1 )` (because of [this trig identity](https://www.mathway.com/popular-problems/Trigonometry/300305)).
7. Rearranging, `(Rd/H0)^2 = (H0^2 + rd0^2) / H0^2 = 1 + ( rd0 / H0 )^2`
8. Subbing in `Rs` and `Rd` from above, I've created a function for calculating the lift distance needed in my local `PolyGear.scad` that looks like this:
    ```
    function calc_lift(H0, r0, rd0) = ( sqrt(H0^2+r0^2) - sqrt(H0^2+rd0^2) ) / sqrt(2 + (rd0/H0)^2);
    ```

Unfortunately some part of this process is incorrect! This doesn't lift the correct amount.

For a bevel gear created like this: `bevel_gear(w=1, m=1, ded=0);` the function above lifts by `0.479855` but by eyeballing it, it should be near `0.7813`.

Can anyone familiar with this library help me understand how to calculate the lift amount? (or fix my logic above?)

**Comment by dpellegr** [comment]
Hi, I didn't go through all your derivation but a problem is likely the fact that I oversimplified it in the FAQ. 

In reality the code does not _project_ on a sphere, but _folds_ on a sphere. The difference being that this transformation preserves the length, like taking a string and wrapping it around a cylinder.

I had this issue raised privately in the past. The person was able to quickly make progress by duplicating the bevel module and replacing the construction of the polyhedron with a search for the minimum z of the vertex cloud (after having changed it into a function).

I committed myself to find a different construction, so that the resulting bevel position is more predictable. I've found the problem tricky, but I made progress and I hope to be able to finalize this work and push it here soon.

**Comment by jphastings** [comment]
That's great, thank you so much, this is an excellent library!

**Comment by dpellegr** [comment]
I still haven't managed to find an alternative construction which satisfies me.
Therefore, for the time being, I have added a lightweight function to perform the computation of the z, it is called `bevel_gear_z_offset`.
I kept it quite verbose, so that the steps that it carries out should read pretty easily.

**Comment by jphastings** [comment]
This is superb! Thank you :) We can close this issue, if you like?
